### ISSUE TITLE
Solar rooftop in QLD returning 0 value, also appears to affect total generation figure

### ISSUE THREAD

**Issue by bdii** [bacco007/sensor.opennem#12]
using latest version of OpenNEM component (2022.02.1), and HA Core/OS on Rpi

For QLD the OpenNEM component is returning 0 for the rooftop solar (since Feb 4th). The total generation figure also appears to be missing the roof top solar component as it is approx. that much less than the value shown on Nemwatch (allowing for time lag between Nemwatch and my system) where the small solar value is shown. The OpenNEM website is also showing the small/rooftop solar production for QLD.

However, it appears that the CO2signal integration is also not including the small/rooftop solar figure in it's calculations as the % FF for QLD peaks and troughs for using the OpneNEM data and CO2signal integration data have very similar values, albeit due to better granularity the falls and rises occur earlier in the day for Opennem. The daily lows are around 70% FF for both, whereas previously they were around 50%.

So maybe the issue lies with the source OpenNEM API?

In addition, the emission factor for QLD has remained constant at 0.7596 since it became available via the component on my system (Feb 8th). I expected it to vary during the day as the composition of the generation sources changed. 

All other data appears to be consistent with the equivalent time point data on the Nem watch website

**Comment by bacco007** [comment]
I only noticed yesterday mine had stopped too, looking back at the data it doesn't appear to be related to the new version (it was reporting 0 beforehand) rather a change in the upstream API.

With the Rooftop Solar - I think I've identified the issue and a potential solution - testing something at the moment that if it works, I should have out tonight.

I'll have to have a look at the emission factor in greater detail

**Comment by DavidFW1960** [comment]
solar rooftop is completely missing in NSW...

**Comment by bacco007** [comment]
Thats odd - its reporting ok on my setup

![Screen Shot 2022-02-11 at 09 48 08 am](https://user-images.githubusercontent.com/6810572/153509778-608fab30-6453-49ef-bfb4-e38490cbeb2d.png)

**Comment by DavidFW1960** [comment]
Yeah it's showed up here now as well It was unknown before...
