### ISSUE TITLE
Sensor stopped updating at 3:31am this morning

### ISSUE THREAD

**Issue by kineticscreen** [bacco007/sensor.opennem#2]
Nothing much more to add - value froze at last update of 3:31:16

![image](https://user-images.githubusercontent.com/39250334/139753989-5df059e9-b2e2-46de-bd3d-b1a7bee0ff65.png)

**Comment by tkrull75** [comment]
same issue here on the NSW spot price

![image](https://user-images.githubusercontent.com/67085433/139770657-b48dcaee-1d0a-4818-9709-5e39b8b078f0.png)

**Comment by kineticscreen** [comment]
Unfortunately rebooting hasn't fixed it. It briefly came back to life on its own for a couple of values between 12:15 and 12:21, but restarting it just now hasn't woken it up.
![image](https://user-images.githubusercontent.com/39250334/139782507-e27b28fb-c582-44c3-8caa-5bd7cfc03a7f.png)

**Comment by tkrull75** [comment]
if you check on OpenNEM for VIC, the price is actually 0 at the moment, so this may be why?

**Comment by kineticscreen** [comment]
Will keep an eye on it. Definitely froze overnight, but perhaps the restart _has_ fixed it, but now the price is stuck at 0 anyway!

**Comment by bacco007** [comment]
OpenNEM is reporting the price in NSW as zero at the moment - not sure whats happened, but it seems to be upstream

**Comment by kineticscreen** [comment]
Is there still a problem with the data source? The update frequency has been garbage for days now.

**Comment by bacco007** [comment]
It appears so - i'll have a look over the weekend and see if there is anything we can do to mitigate it
