### ISSUE TITLE
Price attribute has frequent incorrect 0 values

### ISSUE THREAD

**Issue by kineticscreen** [bacco007/sensor.opennem#9]
I noticed this starting to happen before the recent big update, so I don't think it's a bug that's come from the rewrite, but the value of the Price field - at least for Victoria - frequently has erroneous zero values:

![image](https://user-images.githubusercontent.com/39250334/151266856-e2afd8e9-7e7e-453d-b9b4-4a3dac91fc53.png)

Unlike some other recent issues, this doesn't appear to be reflected in the OpenNEM data:
![image](https://user-images.githubusercontent.com/39250334/151266954-dedf458f-6574-41d9-b7d3-adaa78450d5b.png)

**Comment by bacco007** [comment]
I've been looking into this - its a tad frustrating how this works (some regions seem to be more susceptible to reporting zeros than others) - I might have a fix though, just need to test it.

**Comment by kineticscreen** [comment]
Nice one, let me know if there's anything I can do to help / test.

**Comment by kineticscreen** [comment]
Looking good so far

**Comment by tkrull75** [comment]
Hi - I noticed the price attribute zero value seems to be fixed now so thanks for that :-), but for me, as of yesterday I am having issues with NSW demand showing zero - doesn't appear to be reflected in openNEM

![image](https://user-images.githubusercontent.com/67085433/152072040-b4846364-35b1-4552-9595-f52ac56823af.png)

**Comment by bacco007** [comment]
The API is reporting zero for demand in NSW at the moment - not sure why, seems to be an issue at OpenNEM's end
